import math


EPS = 1e-8


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1]


def det(a, b):
    return a[0] * b[1] - a[1] * b[0]


def norm(v):
    return math.sqrt(dot(v, v))


def normalize(v):
    n = norm(v)

    if n < EPS:
        return (0.0, 0.0)

    return (v[0] / n, v[1] / n)


def compute_orca_constraint(
    p_a,
    v_a,
    p_b,
    v_b,
    radius,
    time_horizon,
    dt
):
    """
    Compute the ORCA constraint generated by B for A.

    Returns:
        line_point: point on the ORCA boundary
        line_direction: direction parallel to the ORCA boundary
        u: minimum correction of the relative velocity
    """

    # --------------------------------------------------
    # RELATIVE QUANTITIES
    # --------------------------------------------------

    relative_position = (
        p_b[0] - p_a[0],
        p_b[1] - p_a[1]
    )

    relative_velocity = (
        v_a[0] - v_b[0],
        v_a[1] - v_b[1]
    )

    dist_sq = dot(
        relative_position,
        relative_position
    )

    combined_radius = 2.0 * radius
    combined_radius_sq = combined_radius ** 2

    # --------------------------------------------------
    # CASE 1: DRONES ARE NOT CURRENTLY COLLIDING
    # --------------------------------------------------

    if dist_sq > combined_radius_sq:

        inv_tau = 1.0 / time_horizon

        # Vector from the cutoff-circle centre
        # to the current relative velocity
        w = (
            relative_velocity[0]
            - inv_tau * relative_position[0],

            relative_velocity[1]
            - inv_tau * relative_position[1]
        )

        w_length_sq = dot(w, w)

        dot_wp = dot(
            w,
            relative_position
        )

        # ----------------------------------------------
        # Projection on cutoff circle
        # ----------------------------------------------

        if (
            dot_wp < 0.0
            and dot_wp * dot_wp
            > combined_radius_sq * w_length_sq
        ):

            w_length = math.sqrt(w_length_sq)

            if w_length < EPS:
                unit_w = (0.0, 0.0)
            else:
                unit_w = (
                    w[0] / w_length,
                    w[1] / w_length
                )

            line_direction = (
                unit_w[1],
                -unit_w[0]
            )

            u = (
                (
                    combined_radius * inv_tau
                    - w_length
                ) * unit_w[0],

                (
                    combined_radius * inv_tau
                    - w_length
                ) * unit_w[1]
            )

        # ----------------------------------------------
        # Projection on one of the VO legs
        # ----------------------------------------------

        else:

            leg = math.sqrt(
                dist_sq - combined_radius_sq
            )

            if det(relative_position, w) > 0.0:

                # Left leg
                line_direction = (
                    (
                        relative_position[0] * leg
                        - relative_position[1] * combined_radius
                    ) / dist_sq,

                    (
                        relative_position[0] * combined_radius
                        + relative_position[1] * leg
                    ) / dist_sq
                )

            else:

                # Right leg
                line_direction = (
                    -(
                        relative_position[0] * leg
                        + relative_position[1] * combined_radius
                    ) / dist_sq,

                    (
                        relative_position[0] * combined_radius
                        - relative_position[1] * leg
                    ) / dist_sq
                )

            projection = dot(
                relative_velocity,
                line_direction
            )

            u = (
                projection * line_direction[0]
                - relative_velocity[0],

                projection * line_direction[1]
                - relative_velocity[1]
            )

    # --------------------------------------------------
    # CASE 2: ALREADY COLLIDING
    # --------------------------------------------------

    else:

        inv_dt = 1.0 / dt

        w = (
            relative_velocity[0]
            - inv_dt * relative_position[0],

            relative_velocity[1]
            - inv_dt * relative_position[1]
        )

        w_length = norm(w)

        if w_length < EPS:
            unit_w = (1.0, 0.0)
        else:
            unit_w = (
                w[0] / w_length,
                w[1] / w_length
            )

        line_direction = (
            unit_w[1],
            -unit_w[0]
        )

        u = (
            (
                combined_radius * inv_dt
                - w_length
            ) * unit_w[0],

            (
                combined_radius * inv_dt
                - w_length
            ) * unit_w[1]
        )

    # --------------------------------------------------
    # RECIPROCAL RESPONSIBILITY
    # --------------------------------------------------

    line_point = (
        v_a[0] + 0.5 * u[0],
        v_a[1] + 0.5 * u[1]
    )

    return line_point, line_direction, u

def choose_orca_velocity(v_pref, line_point, line_direction, max_speed):
    """
    Select the velocity closest to v_pref
    that satisfies one ORCA half-plane.
    """

    # Normal pointing toward the allowed side
    normal = (
        -line_direction[1],
        line_direction[0]
    )

    relative = (
        v_pref[0] - line_point[0],
        v_pref[1] - line_point[1]
    )

    violation = dot(relative, normal)

    # --------------------------------------------------
    # Preferred velocity is outside the allowed region
    # --------------------------------------------------

    if violation < 0.0:

        v_new = (
            v_pref[0] - violation * normal[0],
            v_pref[1] - violation * normal[1]
        )

    else:

        v_new = v_pref

    # --------------------------------------------------
    # Enforce maximum speed
    # --------------------------------------------------

    speed = norm(v_new)

    if speed > max_speed:

        v_new = (
            v_new[0] / speed * max_speed,
            v_new[1] / speed * max_speed
        )

    return v_new
